static const cl_uint
    ROWS_BLOCKDIM_X   = 16, COLUMNS_BLOCKDIM_X = 16,
    ROWS_BLOCKDIM_Y   = 4,  COLUMNS_BLOCKDIM_Y = 8,
    ROWS_RESULT_STEPS = 8,  COLUMNS_RESULT_STEPS = 8,
    ROWS_HALO_STEPS   = 1,  COLUMNS_HALO_STEPS = 1;

